# See https://ezcv.readthedocs.io for documentation
name: Utkarsh Raj
theme: dimension
resume: false
biography: Hey! this is Utkarsh. This is an attempt to write a non-generic non-pretentious introduction about myself. I don't have any idea how to start. So, its better to just go to my LinkedIn where you will find all the pretentious stuff. 
background: max-kuntscher-Cpb2HY41bs8-unsplash.jpg
avatar: dp.jfif
email: utkarsh.sendmail@gmail.com
phone: 8877633383
blog: true
blog_link: https://thinkstraight.substack.com/
social: true
twitter_embed_url: https://twitter.com/utk_tweeting?ref_src=twsrc%5Etfw
projects: 
  {0:
    {'title':'Investor Table',
      'link': 'https://airtable.com/embed/shrnPlOx4pF2U0Ed8?backgroundColor=blue&viewControls=on'},
   1:{'title':'Startup Table',
      'link': 'https://airtable.com/embed/shrkQoe33gMMyoTcC?backgroundColor=blue&viewControls=on'}   
  }
