# See https://ezcv.readthedocs.io for documentation
name: Utkarsh Raj
theme: dimension
resume: false
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines
background: https://i.pinimg.com/originals/17/b8/66/17b8669917485ee73510c5cfa5d8b0e6.jpg
avatar: dp.jfif
email: utkarsh.sendmail@gmail.com
phone: 8877633383
blog: true
blog_link: https://thinkstraight.substack.com/
twitter_embed_url: <a class="twitter-timeline" href="https://twitter.com/utk_tweeting?ref_src=twsrc%5Etfw">Tweets by utk_tweeting</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>