# See https://ezcv.readthedocs.io for documentation
name: Utkarsh Raj
theme: dimension
resume: false
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines
background: https://i.pinimg.com/originals/17/b8/66/17b8669917485ee73510c5cfa5d8b0e6.jpg
avatar: dp.jfif
email: utkarsh.sendmail@gmail.com
phone: 8877633383
blog: true
blog_link: https://thinkstraight.substack.com/
social: true
twitter_embed_url: https://twitter.com/utk_tweeting?ref_src=twsrc%5Etfw
projects: 
  {0:
    {'title':'Investor Table',
      'link': 'https://airtable.com/embed/shrnPlOx4pF2U0Ed8?backgroundColor=blue&viewControls=on'},
   1:{'title':'Startup Table',
      'link': 'https://airtable.com/embed/shrkQoe33gMMyoTcC?backgroundColor=blue&viewControls=on'}   
  }